firmware-qcom-boot-kaanapali: fix LICENSE.txt fetch after FW_BUILD_ID removal
Commit 3c9ace01 ("firmware-qcom-boot-kaanapali: align SRC_URI with other
recipes") dropped the FW_BUILD_ID variable definition but left the
LICENSE.txt SRC_URI entry referencing it. With the variable undefined,
the URL contains a literal ${FW_BUILD_ID} and do_fetch fails:

  ERROR: firmware-qcom-boot-kaanapali-00009.1-r0 do_fetch: Bitbake
  Fetcher Error: FetchError('Unable to fetch URL from any source.', ...)

Inline the path FW_BUILD_ID used to expand to, restoring the previous
download URL and matching the inlined style of the bootbinaries entry.

Fixes: https://github.com/qualcomm-linux/meta-qcom/issues/2770

Signed-off-by: Ricardo Salveti <ricardo.salveti@oss.qualcomm.com>
(cherry picked from commit 98792905c4b4454eb855371d1549b750133ce0ab)